#!/usr/bin/env bash
# Uses Hack Nerd Font
# Modified version of Luke Smith's dwmblocks

# Tunel
[ -n "$(cat /sys/class/net/tun*/operstate 2>/dev/null)" ] && tunel="󰌾"

# Ethernet
[ "$(cat /sys/class/net/e*/operstate 2>/dev/null)" = 'up' ] && ethernet="󰈀"

# Wifi
[ "$(cat /sys/class/net/w*/operstate 2>/dev/null)" = "up" ] && wifi=""

echo "$(echo "$tunel$ethernet$wifi" | awk '$1=$1' FS= OFS=" ")$(awk '/^\s*w/ { print " " int($3*100/70) "%" }' /proc/net/wireless)"
