#!/usr/bin/env bash
# Modified version of Luke Smith's dwmblocks

# current brightness
curr_brightness=$(cat /sys/class/backlight/*/brightness)

# max_brightness
max_brightness=$(cat /sys/class/backlight/*/max_brightness)

# brightness percentage
brightness_per=$((100 * curr_brightness / max_brightness))

echo " ${brightness_per}%"
